source: ./demo-site

exclude: ["Gemfile", "Gemfile.lock", "node_modules", ".idea", ".git", "_site"]

keep_files:
 - "assets"

# Serving
host: 0.0.0.0
port: 4000

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
