version: "3"

services:
  site:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 4000:4000
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      JEKYLL_ENV: development
    command: jekyll serve --watch --force_polling