version: "3"

services:
  site:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    tty: true
    ports:
      - 4000:4000
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      JEKYLL_ENV: development
    entrypoint: /code/docker-entrypoint.sh
