version: "3"

services:
  site:
    build:
      dockerfile: ./Dockerfile
      context: ./
    tty: true
    ports:
      - 4000:4000
    volumes:
      - ./:/code
    environment:
      JEKYLL_ENV: preview
    entrypoint: /code/docker-entrypoint.sh

  assets:
    image: node:9
    volumes:
      - ./:/code
    working_dir: /code
    command: yarn run build:docker-compose-preview
