version: "3"

services:
  site:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
    environment:
      JEKYLL_ENV: development
    command: jekyll serve --watch --force_polling